### PR TITLE
The Great Serial Simplification

### PR DESCRIPTION
**Pull request by robintown**
This updates serial frames to reflect the simplified system found in [Miscellanea #1](https://toaqlanguage.wordpress.com/2021/08/08/miscellanea1/).

The only changes are to frames; I've avoided making changes to the place structures of any words, but later on we may want to consider making changes to sỏq, dỏa, jẻa, dủı, chỉa, etc. to restore their earlier serial behavior. I've also kept around `c c 2` for the moment since it seems useful and I wasn't sure what else to do with it.

The tentative new namesakes are GI, MUOQ, TUA, LEO, CHEO, DUASUE, HUAQ, and JEQ. I'm open to other suggestions.

### CODE REVIEW

**Review by uakci — APPROVED** [review]
Very nice, thank you for your `commit`ment (get it?).

I’d suggest rebasing the commits now, in particular merging the two commits that touch namesakes (remove & add) such that they appear as one. And so that the merge branch commits are gone.

**Comment by robintown** [comment]
Honestly I tend to avoid doing rebases to things I've already pushed, and the history here feels pretty clean to me, so I'm going to leave it alone for the moment unless @solpahi wants it rebased too

**Comment by uakci** [comment]
> Honestly I tend to avoid doing rebases to things I've already pushed

Sorry, I don’t understand this line of reasoning. All the way up until the point a PR is decreed final, one can always rebase its contents. Not rebasing them now means that what gets merged into the final repository will contain junk. And I absolutely see the merge commits at the very least junk. (I don't care that much for the namesake commits.)

Unless you don’t care, in which case I will comply. (I guess it’s not an end-the-world issue after all.)

**Comment by robintown** [comment]
OK, I've rebased, though I've kept the namesake commits as-is since it makes more sense to me to re-add them only once all the frame changes are done

**Review by uakci — APPROVED** [review]
Looks good to me now, thank you.

**Review by solpahi — APPROVED** [review]

**Pull request merged**
