### PR TITLE
adding «poı»

### PR DESCRIPTION
**Pull request by uakci**
«poı» is a well-known and commonly used word; therefore, it deserves incorporating into the official dictionary.

### CODE REVIEW

**Comment by acotis** [comment]
IMO, that logic isn't quite sound.  «poi» isn't like other words, and is therefore including or excluding it is a minor-to-moderate design decision that should be left to Hoemai.

**Comment by ciuak** [comment]
> «poi» isn't like other words

It is like «pe», even if it does not share the frame.

**Comment by ciuak** [comment]
oh, and I forgot:

> therefore including or excluding it is a minor-to-moderate design decision that should be left to Hoemai.

This is why I am submitting this as a PR. I won't commit to the repository directly, because we're trusted and expected not to make abrupt changes to what is soon becoming *the* official dictionary.

My expectation is that Hoemāı should be the one doing the merging, if at all.

**Comment by acotis** [comment]
I think I agree with you that it's like «pe» in the sense that it "picks apart" a proposition and makes claims about its participants, so I'll retreat back 10 yards and point out that it's basically a function word that adds a new "type" of sentence into Toaq.  So I'll still abstain for now :P

**Comment by uakci** [comment]
Superseded by <https://github.com/toaq/dictionary/commit/4a423d40f7ad8917e5052a114485064595994a7e>.

**Pull request closed without merging**
