### PR TITLE
Adding tıtūa, tıshēa, cajōı and gaıshō.

### PR DESCRIPTION
**Pull request by Ntsekees**

### CODE REVIEW

**Comment by uakci** [comment]
cc @solpahi: If this request reaches 7-day inactivity and the reviews are mostly positive, and there’s no negative feedback from solpahi, I will merge this Pull Request. I will do this with every PR from now on so they don’t wait too long for their turn.

**Comment by acotis** [comment]
The definition of **cajoi** given in this PR is `[] happens for purpose []`, but I think that that's out of sync with its etymology, which suggests the definition `Cả ru ȷỏı [] []`. 

The rest of the content looks good. Regarding merging policy, I would suggest to @uakci that the default action be to not merge until Hoemai expresses approval, since the stuff in this repo ends up labeled by Toadua as "official".

**Comment by uakci** [comment]
As for the merging policy: If solpahi made visits to this repository more often and commented and shared his opinion more, I’d never need to ‘auto-merge’. We currently have 45 open issues, an overwhelming majority of which waiting for solpahi to make a decision. I don’t presume that solpahi’ll change his mode of action in the foreseeable future, so for now, I had better he vetoed rather than approved. cc @acotis

**Comment by uakci** [comment]
As for **cajōi**, I think it’s the only sensible word for ‘x happens for purpose y’, even though its word form doesn’t match the meaning. Maybe **joicā**?

**Comment by acotis** [comment]
> As for cajōi, [...]

So, this word comes from the toaq.org translation of The White Snake:

> ju kủi hóq lû rúaijōaq rào bû mủo gẻqsīa bi, jỉainūa fãqsīa hó tíechūo **càjōi chûq** da.

Which is translated as: 

> for the king never took off the cover **to eat of it** until he was quite alone. 

But I think the semantics of "in order to" are going to get a **poi**-like eventually, which would render this predicate unnecessary. I also don't think this particular formulation makes much sense; is "purpose" really a feature of events? I think it's a feature of agents, which an event can have zero, one, or many of. (cf `shiutao` and friends).

**Comment by acotis** [comment]
> As for the merging policy: If solpahi made visits to this repository more often and commented and shared his opinion more, I’d never need to ‘auto-merge’. [...]

Maybe this is petty, but I would like to register my fairly strong disapproval of this one last time for posterity. Official Toaq moving too slowly for your tastes is not a good reason to start calling your own stuff official. I can't speak for Hoemai, but I would find it infuriating if somebody started saying that X or Y was official in my conlang when it wasn't.

**Comment by uakci** [comment]
> cajōi

Nice detective work. And while I disagree that purpose requires an agent, I do agree that it requires somebody to assign purpose (**jìe**). People assign meaning to arbitrary things which might not necessarily have been caused by a thinking agent. Note that **kui** has similar semantics and frame structure, and happens to be the opposite.

> policy stuff

How can I address this… If solpahi wanted nobody to work on anything publicly, he wouldn’t have had his dictionary transported to a public space where everybody gets a say. And if everybody gets a say, then everybody should have a chance to express their opinions and share their proposals. But if solpahi’s reaction to my opinions and proposals (and not just mine!) is nil, then what does that make of my ability to ‘express’ and ‘suggest’? I decided, instead of forcing my commits down solpahi’s throat, to give *seven* days of wait. If solpahi cares, he will have reacted to a proposal by then. I don’t see why I should consider his hypothetical protests to decisions made in this room here when he consciously stays away from the room. If solpahi should disagree, then the only sensible solution I see is for him to restrict write access to him. Otherwise, it’s just a waste of time — and I haven’t gone through every root for nothing!

**Comment by Ilmen-vodhr** [comment]
I don't like **cajōı** myself, but I added it to the pull request because it appears in the Sample Text.

As for policy, I agree with @acotis that we should wait for @solpahi's approval. Having the dictionary on GitHub allows us to easily send pull requests, like I've done with that very one here. We have the implicit permission to edit files directly (as @solpahi could have configured the repository to disallow it), but I'd use that privilege with parsimony, only to correct typo and obvious errors, until @solpahi issues a different policy, I'd say.

You could create a second branch containing "community approved" stuff, recording dialectal Toaq, Toaq as we use it.

**Comment by uakci** [comment]
Let us wait for solpahi to issue a policy, then.

**Comment by lynn** [comment]
We have **puoq** now instead of **cajoı**.

On the two year old subject of policy, Hoemaı said this on Discord:

>  I have no opinion on [making **cuoı** official], but I do want to say that I don't think it's very important whether a word is official or not. Really, my main vision for the official dictionary was that it contain a solid core of well-described words (read: all the fields in the .json properly filled in), and not so much a way to split the lexicon into real words and less real words (not that anyone was thinking that). By now dictionary.json contains so many non-core words that it's unlikely to ever be filled in the way I imagined, and its purpose has shifted a bit towards documenting technical details like frames (which is also useful of course). 
> 
> Bottom line: just keep making words yourself (non-personal you). If you wait for me to make official words, things will end up like with the words for "push" and "pull", which never came.

**Review by niftg — APPROVED** [review]

**Comment by uakci** [comment]
Do we have an update on this PR? **cajoı** should now be obsolete to **zuo** (previously **puoq**). The other three words should be good to keep.

**Pull request closed without merging**
